### ISSUE TITLE
[Suggestion] Wandering Wizard hat a little lower on the player head

### ISSUE THREAD

**Issue by avilonlegends** [kend1e/FANTASY-ARMOR#7]
Hi there!

Your armors are really amazing! I only wanted to ask if perhaps it would be possible to move the model of the Wandering Wizard Helmet a little further down on the head? It looks just a little bit like it's barely touching the head of the player character.

I'm sorry for bothering you with this, you don't have to change this if you don't want to, of course! 

Thank you for the great mod regardless!

**Comment by kend1e** [comment]
Hi! I think I won't change it, because otherwise the player's head overlay will be out of the hat. I could make the bottom level of the hat bigger, but then I don't really like the way it looks. Anyway, thank you!

<img width="539" alt="17-12-2024_18-41" src="https://github.com/user-attachments/assets/f39cf803-3de1-47ce-bfe3-8aa1d117b92c" />
